Add printing GDScript variables & fix setting variables
AnidemDex/Blockflow pull request #153
Opened 2024-05-20 14:05 UTC by supastishn

Currently, print only works on strings, and setting variables didn't work due to ``object.set()`` not adding variables on runtime.
I fixed setting variables by first checking if the variable is an original variable on the node, if it is, set the variable, otherwise, add a variable using metadata.
To print variables, I simply used ``object.get()`` to print a variable, and ``object.get_meta()`` to get metadata to print metadata variables.

2024-05-20 14:06 UTC, supastishn commented
I am aware I shouldn't have grouped these together, but I forgot, sorry

2024-05-20 20:26 UTC, AnidemDex requested changes

2024-05-20 20:26 UTC, AnidemDex commented on icons/group.svg.import
To avoid populating the commit unnecessarily, we should mark cloned .import files as unchanged locally. More on that later

2024-05-21 03:06 UTC, supastishn commented on collection.gd
Maybe? I prefered collection aas it felt more "global"

2024-05-21 03:06 UTC, supastishn commented on command_collection.gd
Sorry, sometimes I accidentally add or remove depending on my code, im gonna fix them

2024-05-21 03:08 UTC, supastishn commented on commands/command.gd
> +
what

2024-05-21 03:10 UTC, supastishn commented on core/utils.gd
> +			data[&"initial_collection"] = get_object_data(object.initial_collection)
Sorry, this was an artefact of a find and replace I did, essentially main_collection and initial were the same thing so i made them all initial

2024-05-21 04:22 UTC, supastishn commented
I fixed some issues with setting block clashing with the addition, division and multiplication (as sometimes it sets meta not sets the actual variable)
The PR right now should be fully featured for now, but I might add regex to printing soon, unsure however. There's a demo video I shot and sent on discord (It's too big for github)

2024-05-21 15:13 UTC, AnidemDex commented on collection.gd
If only commands uses it, maybe it should be in commands. If it modifies the command behavior or execution steps, it should be in the processor. If is related to collection to modify the collection itself, it goes here

2024-05-21 15:14 UTC, AnidemDex commented on command_collection.gd
We try to (loosely) follow the same guideline that Godot uses. A single line is ok

2024-05-21 15:20 UTC, AnidemDex reviewed
I'll write to you to discuss some implementations

2024-05-30 16:13 UTC, supastishn commented
(Don't worry about the force push, I copy the folder directly from project and delete *.import so git is weird)

2024-06-01 16:58 UTC, supastishn commented
Mistake in commit message: I didn't just add square root, the nth root is available too, so you could theoretically get the 2763rd root of something if you want

2024-06-05 00:03 UTC, AnidemDex commented
I can't push changes to the branch to solve the review goddamn github

2024-06-05 00:19 UTC, AnidemDex requested changes
I'll do those in order to merge dw

2024-06-05 00:19 UTC, AnidemDex commented on commands/command.gd
> +func _add_variable(varname: String, vartype, varvalue, target_node: Node):
must be `property` unless we are creating a new term in the plugin (`variable`)

2024-06-05 00:19 UTC, AnidemDex commented on commands/command_set.gd
> +const Operables = [
This is a breaking change since is not private _and_ is a constant value

2024-06-05 00:49 UTC, AnidemDex commented on commands/command_print.gd
> +	if target_node.get(variable) != null: print(target_node.get(variable))
variable _can_ be null if is `Object` type

2024-06-05 00:58 UTC, AnidemDex commented on commands/command_set.gd
> -var add_value:bool = false:
This one was deprecated too, better to just mark as deprecated instead of removing

2024-06-10 16:01 UTC, AnidemDex commented on commands/command_set.gd
> -var add_value:bool = false:
no needed

2024-06-10 16:04 UTC, AnidemDex commented on commands/command_print.gd
> +	if target_node.get(variable) != null: print(target_node.get(variable))
we can solve this in another pr

2024-06-10 16:04 UTC, AnidemDex approved these changes
Seems good

2024-06-10 16:07 UTC, merged